version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: club_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: club_database
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql  # Montar el archivo SQL en el contenedor
      

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: club_web
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:rootpassword@mysql/club_database"
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - club_network

networks:
  club_network:
    driver: bridge

